# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.models.graph_db_repository import GraphDBRepository  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestGraphDBRepository(unittest.TestCase):
    """GraphDBRepository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGraphDBRepository(self):
        """Test GraphDBRepository"""
        # FIXME: construct object with mandatory attributes with example values
        # model = graphdb.graphdb_workbench.models.graph_db_repository.GraphDBRepository()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
