# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from graphdb import graphdb_workbench
from graphdb.graphdb_workbench.models.access_bean import AccessBean  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestAccessBean(unittest.TestCase):
    """AccessBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessBean(self):
        """Test AccessBean"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.access_bean.AccessBean()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
