# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.api.sql_views_controller_api import SqlViewsControllerApi  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestSqlViewsControllerApi(unittest.TestCase):
    """SqlViewsControllerApi unit test stubs"""

    def setUp(self):
        self.api = graphdb.graphdb_workbench.api.sql_views_controller_api.SqlViewsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sql_view_using_post(self):
        """Test case for create_sql_view_using_post

        Create a new SQL view  # noqa: E501
        """
        pass

    def test_delete_sql_view_using_delete(self):
        """Test case for delete_sql_view_using_delete

        Delete an existing saved query  # noqa: E501
        """
        pass

    def test_get_sql_view_names_using_get(self):
        """Test case for get_sql_view_names_using_get

        Get all SQL view names for current repository.  # noqa: E501
        """
        pass

    def test_get_sql_view_using_get(self):
        """Test case for get_sql_view_using_get

        Get a SQL view configuration.  # noqa: E501
        """
        pass

    def test_update_sql_view_using_put(self):
        """Test case for update_sql_view_using_put

        Edit an existing SQL view  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
