# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.api.saved_queries_controller_api import SavedQueriesControllerApi  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestSavedQueriesControllerApi(unittest.TestCase):
    """SavedQueriesControllerApi unit test stubs"""

    def setUp(self):
        self.api = graphdb.graphdb_workbench.api.saved_queries_controller_api.SavedQueriesControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_query_using_post(self):
        """Test case for create_query_using_post

        Create a new saved query  # noqa: E501
        """
        pass

    def test_delete_sample_query_using_delete(self):
        """Test case for delete_sample_query_using_delete

        Delete an existing saved query  # noqa: E501
        """
        pass

    def test_edit_sample_query_using_put(self):
        """Test case for edit_sample_query_using_put

        Edit an existing saved query  # noqa: E501
        """
        pass

    def test_get_queries_using_get(self):
        """Test case for get_queries_using_get

        Get all saved queries visible for the user or single saved query by name and owner.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
