# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.api.repository_management_controller_api import RepositoryManagementControllerApi  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestRepositoryManagementControllerApi(unittest.TestCase):
    """RepositoryManagementControllerApi unit test stubs"""

    def setUp(self):
        self.api = graphdb.graphdb_workbench.api.repository_management_controller_api.RepositoryManagementControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repository_using_post(self):
        """Test case for create_repository_using_post

        Create a repository in an attached Sesame location (ttl file)  # noqa: E501
        """
        pass

    def test_delete_repository_using_delete(self):
        """Test case for delete_repository_using_delete

        Delete a repository in an attached Sesame location  # noqa: E501
        """
        pass

    def test_download_repository_config_turtle_using_get(self):
        """Test case for download_repository_config_turtle_using_get

        Download repository configuration as a Turtle file  # noqa: E501
        """
        pass

    def test_download_repository_config_zip_using_get(self):
        """Test case for download_repository_config_zip_using_get

        Download repository configuration as a zip file  # noqa: E501
        """
        pass

    def test_edit_repository_using_put(self):
        """Test case for edit_repository_using_put

        Edit repository configuration  # noqa: E501
        """
        pass

    def test_get_default_config_using_get(self):
        """Test case for get_default_config_using_get

        Get the default repository configuration for the repository type  # noqa: E501
        """
        pass

    def test_get_repositories_using_get(self):
        """Test case for get_repositories_using_get

        Get all repositories in the active location or another location  # noqa: E501
        """
        pass

    def test_get_repository_config_json_using_get(self):
        """Test case for get_repository_config_json_using_get

        Get repository configuration as JSON  # noqa: E501
        """
        pass

    def test_repository_size_using_get(self):
        """Test case for repository_size_using_get

        Get repository size  # noqa: E501
        """
        pass

    def test_restart_repository_using_post(self):
        """Test case for restart_repository_using_post

        Restart a repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
