# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.api.location_management_controller_api import LocationManagementControllerApi  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestLocationManagementControllerApi(unittest.TestCase):
    """LocationManagementControllerApi unit test stubs"""

    def setUp(self):
        self.api = graphdb.graphdb_workbench.api.location_management_controller_api.LocationManagementControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_location_using_post(self):
        """Test case for activate_location_using_post

        Activate a connected GraphDB location  # noqa: E501
        """
        pass

    def test_add_location_using_post(self):
        """Test case for add_location_using_post

        Connect to a remote GraphDB location  # noqa: E501
        """
        pass

    def test_change_location_using_put(self):
        """Test case for change_location_using_put

        Modify settings for a connected GraphDB location  # noqa: E501
        """
        pass

    def test_delete_location_using_delete(self):
        """Test case for delete_location_using_delete

        Disconnect a GraphDB location  # noqa: E501
        """
        pass

    def test_get_active_location_using_get(self):
        """Test case for get_active_location_using_get

        Get active connected GraphDB location  # noqa: E501
        """
        pass

    def test_get_all_using_get(self):
        """Test case for get_all_using_get

        Get all connected GraphDB locations  # noqa: E501
        """
        pass

    def test_set_default_repository_using_post(self):
        """Test case for set_default_repository_using_post

        Set default repository for active GraphDB location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
