# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.models.saved_query import SavedQuery  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestSavedQuery(unittest.TestCase):
    """SavedQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSavedQuery(self):
        """Test SavedQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = graphdb.graphdb_workbench.models.saved_query.SavedQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
