# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.models.master_connect_bean import MasterConnectBean  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestMasterConnectBean(unittest.TestCase):
    """MasterConnectBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMasterConnectBean(self):
        """Test MasterConnectBean"""
        # FIXME: construct object with mandatory attributes with example values
        # model = graphdb.graphdb_workbench.models.master_connect_bean.MasterConnectBean()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
