# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.models.location_uri import LocationUri  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestLocationUri(unittest.TestCase):
    """LocationUri unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationUri(self):
        """Test LocationUri"""
        # FIXME: construct object with mandatory attributes with example values
        # model = graphdb.graphdb_workbench.models.location_uri.LocationUri()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
