# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.api.security_management_controller_api import SecurityManagementControllerApi  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestSecurityManagementControllerApi(unittest.TestCase):
    """SecurityManagementControllerApi unit test stubs"""

    def setUp(self):
        self.api = graphdb.graphdb_workbench.api.security_management_controller_api.SecurityManagementControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_user_settings_using_patch(self):
        """Test case for change_user_settings_using_patch

        Change settings for a user  # noqa: E501
        """
        pass

    def test_create_user_using_post(self):
        """Test case for create_user_using_post

        Create a user  # noqa: E501
        """
        pass

    def test_delete_user_using_delete(self):
        """Test case for delete_user_using_delete

        Delete a user  # noqa: E501
        """
        pass

    def test_edit_user_using_put(self):
        """Test case for edit_user_using_put

        Edit a user  # noqa: E501
        """
        pass

    def test_get_all_users_using_get(self):
        """Test case for get_all_users_using_get

        Get all users  # noqa: E501
        """
        pass

    def test_get_user_using_get(self):
        """Test case for get_user_using_get

        Get a user  # noqa: E501
        """
        pass

    def test_is_enabled_free_access_using_get(self):
        """Test case for is_enabled_free_access_using_get

        Check if free access is enabled  # noqa: E501
        """
        pass

    def test_is_enabled_security_using_get(self):
        """Test case for is_enabled_security_using_get

        Check if security is enabled  # noqa: E501
        """
        pass

    def test_set_enable_free_access_using_post(self):
        """Test case for set_enable_free_access_using_post

        Enable or disable free access  # noqa: E501
        """
        pass

    def test_set_enable_security_using_post(self):
        """Test case for set_enable_security_using_post

        Enable or disable security  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
