# coding: utf-8

"""
    GraphDB Workbench API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import graphdb.graphdb_workbench
from graphdb.graphdb_workbench.api.sparql_template_controller_api import SparqlTemplateControllerApi  # noqa: E501
from graphdb.graphdb_workbench.rest import ApiException


class TestSparqlTemplateControllerApi(unittest.TestCase):
    """SparqlTemplateControllerApi unit test stubs"""

    def setUp(self):
        self.api = graphdb.graphdb_workbench.api.sparql_template_controller_api.SparqlTemplateControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sparql_template_using_post(self):
        """Test case for create_sparql_template_using_post

        Create a new SPARQL template  # noqa: E501
        """
        pass

    def test_delete_sparql_template_using_delete(self):
        """Test case for delete_sparql_template_using_delete

        Delete an existing SPARQL template  # noqa: E501
        """
        pass

    def test_get_sparql_template_content_using_get(self):
        """Test case for get_sparql_template_content_using_get

        Get a SPARQL template configuration  # noqa: E501
        """
        pass

    def test_get_sparql_template_i_ds_using_get(self):
        """Test case for get_sparql_template_i_ds_using_get

        Get IDs of all configured SPARQL templates per current active repository  # noqa: E501
        """
        pass

    def test_update_sparql_template_using_put(self):
        """Test case for update_sparql_template_using_put

        Edit an existing SPARQL template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
